---

- hosts: ios
gather_facts: no
connection: local

tasks:
- name: config from file
  ios_config:
    src: "test_config"
    save_when: changed
  register: op

- name: print the result
  debug:
    var: op
