---
- hosts: ios
  gather_facts: no
  connection: local

  tasks:

  - name: backup
    ios_config:
      backup: yes
    tags:
      - backupOption

  - name: run show command.
    ios_command:
      commands: show ip interf b
    register: cmd_op
    tags:
      - show_cmd

  - name: print the cmd op
    debug:
      var: cmd_op
    tags:
      - print_cmd



#ansible-playbook -i inventory tags_explained.yml --tags "backupOption"
#ansible-playbook -i inventory tags_explained.yml --skip-tags "backupOption"
#ansible-playbook -i inventory tags_explained.yml --tags "backupOption" --list-tasks
