---

- hosts: ios
  gather_facts: no
  connection: local

  vars:
    backout: false

  tasks:

  - name: config from file
    ios_config:
      src: "config/{{inventory_hostname}}-backout.config"
      save_when: changed
    register: op
    when: not backout

  - name: print the result
    debug:
      var: op
    when: not backout

  - name: config from file --backout
    ios_config:
      src: "config/{{inventory_hostname}}-backout.config"
      save_when: changed
    register: opBackout
    when: backout

  - name: print the result  --backout
    debug:
      var: opBackout
    when: backout
