---

# This playbook will create vlan 200 on ios device group and will add G0/1, G0/2, G0/3 in it.



- hosts: ios
  gather_facts: no
  connection: local


  tasks:
  - name: create vlan
    ios_vlan:
      vlan_id: 200
      name: test_200
      state: present

  - name: adding interface inside vlan 100
    ios_vlan:
      vlan_id: 200
      interfaces:
        - Gi0/1
        - Gi0/2
