---

- hosts: ios
  connection: local
  gather_facts: yes

  tasks:
  - name: print
    debug:
      msg:
        - "Control machine name:- {{ansible_hostname}}"
        - "group names in inventory:- {{ group_names }}"
        - "inventory hostname on which task is executing:- {{inventory_hostname}}"
        - "Play hosts:- {{play_hosts }}"
        - "inventory_dir :- {{ inventory_dir }}"
        - "inventory File:- {{ inventory_file }}"
